modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_display_name}"
logoFile="logo.png"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forgeconfigapiport"
mandatory=true
versionRange="${forgeconfigapiport_version_range}"
ordering="NONE"
side="CLIENT"
