modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''
${description}
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
